#!/bin/bash

# This will sync the dotfiles from your system to the repo
# Run it from the root of the dotfile repo

# copy MacOS bash configs
rsync -azvh ~/.bash_profile macos/
rsync -azvh ~/.bash_aliases macos/

rsync -azvhr ~/.config/neofetch/ macos/neofetch/
