#!/bin/bash

# This will sync the dotfiles from your system to the repo
# Run it from the appropriate os directory within the dotfile repo

# copy MacOS bash configs
rsync -azvh ~/.bash_profile .
rsync -azvh ~/.bash_aliases .

# copy MacOS zsh configs
rsync -azvh ~/.zshrc .
rsync -azvh ~/.p10k.zsh .

# vimrc
rsync -azvh ~/.vimrc .

# neofetch
rsync -azvhr ~/.config/neofetch/ neofetch/
