#!/bin/bash

# This will sync the dotfiles from your system to the repo
# Run it from the root of the dotfile repo

# copy galliumos bash configs
rsync -azvh ~/.bash_profile .
rsync -azvh ~/.bash_aliases .

rsync -azvhr ~/.config/neofetch/ neofetch/
rsync -azvhr ~/.config/tilix/ tilix/
rsync -azvhr ~/.config/xfce4/ xfce4/
rsync -azvhr ~/.fonts/ fonts/

rsync -azvhr /usr/share/powerline/config_files/ powerline/config_files/
