#!/bin/bash

# This will sync the dotfiles from your system to the repo
# Run it from the root of the dotfile repo

# copy galliumos bash configs
rsync -azvh ~/.bash_profile .
rsync -azvh ~/.bash_aliases .
rsync -azvh ~/.zshrc .
# rsync -azvhr ~/.oh-my-zsh/ .oh-my-zsh/
rsync -azvh ~/.p10k.zsh .


rsync -azvhr ~/.config/neofetch/ neofetch/
# rsync -azvhr ~/.config/tilix/ tilix/
# rsync -azvhr ~/.config/xfce4/ xfce4/
rsync -azvhr ~/.local/share/fonts/ fonts/

# rsync -azvhr /usr/share/powerline/config_files/ powerline/config_files/
